name: PointCLIPV2_LOD
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - pillow
  - tqdm
  - scipy
  - ftfy
  - regex
  - yacs
  - pytorch=1.13
  - torchvision=0.14
  - cudatoolkit=11.7
  - pip:
      - open_clip_torch==2.20.0
      - git+https://github.com/openai/CLIP.git
      - pygltflib
      - trimesh
      - gdown
      - h5py
      - tensorboard
      - tabulate
      - future
      - yapf
      - wilds
      - torch-scatter==2.1.1
