"""Fuse PointNeXt closed-set analysis with PointCLIP V2 open-vocabulary output.

The script writes two files:
1. a merged analysis CSV containing PointNeXt, geometry, and PointCLIP fields;
2. a final LOD-constraint CSV generated by the semantic-structural policy builder.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
from pathlib import Path
from typing import List, Tuple


JOIN_KEYS = ("order", "node_index", "mesh_index")


def parse_args() -> argparse.Namespace:
    project_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description="Fuse PointNeXt and PointCLIPV2 outputs into LOD constraints.")
    parser.add_argument("--pointnext-csv", type=Path, required=True)
    parser.add_argument("--pointclip-csv", type=Path, required=True)
    parser.add_argument("--merged-csv", type=Path, required=True)
    parser.add_argument("--output-csv", type=Path, required=True)
    parser.add_argument("--output-json", type=Path, default=None)
    parser.add_argument("--summary-json", type=Path, required=True)
    parser.add_argument("--project-root", type=Path, default=project_root)
    parser.add_argument("--high-confidence", type=float, default=0.70)
    parser.add_argument("--low-confidence", type=float, default=0.40)
    parser.add_argument("--low-margin", type=float, default=0.08)
    return parser.parse_args()


def load_rows(path: Path) -> List[dict]:
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def key_for(row: dict) -> Tuple[str, str, str]:
    return tuple(str(row.get(key, "")) for key in JOIN_KEYS)


def prefixed_pointclip_row(row: dict) -> dict:
    keep = {
        "pointclip_top1_id",
        "pointclip_top1_name",
        "pointclip_top1_role",
        "pointclip_top1_score",
        "pointclip_top2_id",
        "pointclip_top2_name",
        "pointclip_top2_role",
        "pointclip_top2_score",
        "pointclip_margin",
        "pointclip_topk_json",
    }
    return {key: row.get(key, "") for key in keep}


def merge_rows(pointnext_rows: List[dict], pointclip_rows: List[dict]) -> List[dict]:
    pointclip_by_key = {key_for(row): row for row in pointclip_rows}
    merged = []
    matched = 0
    for row in pointnext_rows:
        clip_row = pointclip_by_key.get(key_for(row))
        out = dict(row)
        if clip_row:
            out.update(prefixed_pointclip_row(clip_row))
            out["pointclip_matched"] = "1"
            matched += 1
        else:
            out.update({
                "pointclip_top1_id": "",
                "pointclip_top1_name": "",
                "pointclip_top1_role": "",
                "pointclip_top1_score": "",
                "pointclip_top2_id": "",
                "pointclip_top2_name": "",
                "pointclip_top2_role": "",
                "pointclip_top2_score": "",
                "pointclip_margin": "",
                "pointclip_topk_json": "",
            })
            out["pointclip_matched"] = "0"
        merged.append(out)
    print(f"Matched PointCLIP rows: {matched}/{len(pointnext_rows)}")
    return merged


def write_csv(path: Path, rows: List[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = []
    seen = set()
    for row in rows:
        for key in row.keys():
            if key not in seen:
                seen.add(key)
                fieldnames.append(key)
    with path.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def load_lod_builder(project_root: Path):
    module_path = project_root / "tools" / "pointnext_lod" / "build_lod_constraints_from_analysis.py"
    spec = importlib.util.spec_from_file_location("lod_builder", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load LOD builder: {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["lod_builder"] = module
    spec.loader.exec_module(module)
    return module


def build_lod_constraints(args: argparse.Namespace, merged_rows: List[dict]) -> List[dict]:
    builder = load_lod_builder(args.project_root)
    thresholds = builder.make_thresholds(merged_rows)
    output_rows = [builder.classify_row(row, thresholds, args) for row in merged_rows]
    summary = builder.summarize(output_rows, thresholds)

    write_csv(args.output_csv, output_rows)
    if args.output_json:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        with args.output_json.open("w", encoding="utf-8") as file:
            json.dump(output_rows, file, ensure_ascii=False, indent=2)
    args.summary_json.parent.mkdir(parents=True, exist_ok=True)
    with args.summary_json.open("w", encoding="utf-8") as file:
        json.dump(builder.counter_to_dict(summary), file, ensure_ascii=False, indent=2)
    return output_rows


def main() -> None:
    args = parse_args()
    pointnext_rows = load_rows(args.pointnext_csv)
    pointclip_rows = load_rows(args.pointclip_csv)
    merged_rows = merge_rows(pointnext_rows, pointclip_rows)
    write_csv(args.merged_csv, merged_rows)
    print(f"Wrote: {args.merged_csv}")
    output_rows = build_lod_constraints(args, merged_rows)
    print(f"Wrote: {args.output_csv}")
    print(f"Wrote: {args.summary_json}")
    counts = {}
    for row in output_rows:
        counts[row["lod_priority"]] = counts.get(row["lod_priority"], 0) + 1
    print("LOD priority counts:")
    for key, value in sorted(counts.items()):
        print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
